name: qr_analyzer
description: A Flutter app to capture or pick images, analyze them via OpenAI, and decode QR codes.

publish_to: "none" 

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  http: ^1.3.0
  qr_code_tools: ^0.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter



